title: Termux Legacy Repo
description: An apt repository for Termux Legacy, install packages that are no longer available in Termux Legacy. This apt repository is not official for Termux.
theme: jekyll-theme-cayman
google_analytics: UA-210931278-2
show_downloads: false
